---
name: "Release: Manual"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      app:
        description: |
          App to release (ex: "radarr"). Set this to "ALL" to rebuild all images and channels.
        default: ""
        required: true
      channels:
        description: "Channels (ex: master,develop)"
        default: "stable"
        required: true
      push:
        description: "Push"
        default: "false"
        required: true
      notify:
        description: "Send notification"
        default: "false"
        required: true

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  determine-images:
    name: Determine Images to Build
    runs-on: ubuntu-22.04
    outputs:
      imagesToBuild: ${{ steps.determine-images.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Determine images to build
        id: determine-images
        shell: bash
        run: |
          if [ "${{ inputs.app }}" = "ALL" ]; then
            ./.github/scripts/fetch.sh all
          else
            output="[]"
            IFS=',' read -a channels <<< "${{ inputs.channels }}"
            declare -a images_array=()
            for channel in "${channels[@]}"; do
              image="$(jo app="${{ inputs.app }}" channel="$channel")"
              images_array+=($image)
            done

            output="$(jo -a ${images_array[*]})"
            echo "changes=${output}" >> $GITHUB_OUTPUT
            echo "Changes:\n ${output}"
          fi

  images-build:
    uses: ./.github/workflows/action-image-build.yaml
    if: needs.determine-images.outputs.imagesToBuild != '[]'
    needs:
      - determine-images
    with:
      imagesToBuild: "${{ needs.determine-images.outputs.imagesToBuild }}"
      pushImages: "${{ github.event.inputs.push }}"
      sendNotification: "${{ github.event.inputs.notify }}"
    secrets: inherit
